### PR TITLE
solved the tutorial issue

### PR DESCRIPTION
**Pull request by michellefilipaa**
used a YouTube link instead

### CODE REVIEW

**Review by DaanSchar — CHANGES_REQUESTED** [review]
there is this package called javafx.scene.web.WebView that my program cannot find so it wont build. did you add anything to the build.gradle that you havent commited?

**Comment by michellefilipaa** [comment]
I didn’t change anything in build.gradle.
The WebView is a package on javafx, not sure why yours isn’t finding it. Is your javafx up to date ?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by FabianBB** [comment]
doesnt work for me either

**Comment by DaanSchar** [comment]
what version of javafx is you usin?

**Comment by michellefilipaa** [comment]
> what version of javafx is you usin?

16.0.2

**Comment by FabianBB** [comment]
im using sdk-11.0.2, ill try upgrading then

**Comment by michellefilipaa** [comment]
it still doesn't work for you guys?

**Pull request merged**
