### PR TITLE
Tile map2

### PR DESCRIPTION
**Pull request by FabianBB**
Tiles are scaled with TileSize now, Constructor changed. Is hexagonal now

### CODE REVIEW

**Comment by DaanSchar** [comment]
looks great.
one thing is that mapX and mapY dont do anything?

**Comment by FabianBB** [comment]
Yea you said you wanted coordinates for the entire map so I just added variables, idk what you needed them for

**Comment by DaanSchar** [comment]
i want to be able to move the whole thing around the screen. so if i set mapX to 100, the whole thing is placed 100 px to the right

**Comment by FabianBB** [comment]
Ok should be done now

**Pull request merged**
