### PR TITLE
Logic winning conditions

### PR DESCRIPTION
**Pull request by Jolijn2020**

### CODE REVIEW

**Review by DaanSchar — CHANGES_REQUESTED** [review]
cannot play the game as when i try to make the first move i get this:
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because "this.actualPlayers[x]" is null

also, after we merge this branch, clean/refactor the code.

**Comment by Jolijn2020** [comment]
everything now works and is tested

**Comment by Giul14** [comment]
test logic Winning Conditions works

**Comment by FabianBB** [comment]
someone merge

**Comment by FabianBB** [comment]
Wrong merge request

**Pull request closed without merging**
